name: Advanced action skills
on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v2
      - uses: actions/checkout@v4
      - run: bun install
      - run: bun test
